# Netlify configuration file

# Form notifications
[build]
  publish = "."

# Configure form notifications to be sent to the site owner
# The email will be sent to jittikas@icloud.com
# Note: You need to set this in Netlify dashboard:
# Site settings > Forms > Form notifications > Email to notify
# Set to: jittikas@icloud.com
